sudo: false
language: python
cache: pip
python:
  - "3.5"
  - "3.6"
notifications:
  email: datasnakes@gmail.com
# command to install dependencies
install:
  - "pip install --upgrade pip setuptools wheel"
  - "pip install --only-binary=numpy,scipy numpy scipy"
  - "pip install matplotlib ipython jupyter sympy pytest>=4.6 codecov pytest-cov"
  - "pip install -r requirements.txt"
  - "pip install ."
# command to run unittests
script:
  - pytest --cov=./
after_success:
  - codecov
