Management_config:
  new_repo: true
  new_user: true
  new_project: true
  new_database: true
  new_research: true
  new_app: false
  new_website: false
  database: 'Test-Database'
  repo: 'Test-Repository'
  user: 'Test-User'
  project: 'Test-Project'
  research: 'Test-Research'
  research_type: 'Test-Research-Type'
  app: 'Test-App'
  website: 'Test-Website'
  host: '0.0.0.0'
  port: '5252'

Database_config:
  email:  "rgilmore@umc.edu"
  driver: "sqlite3"
  GenBank_config:
    download_taxonomy_database:
      db_type: "biosql"
      sub_path: "/refseq/release"
    download_refseq_release_files:
      collection_subset: "vertebrate_mammalian"
      seqtype: "rna"
      filetype: "gbff"
    upload_refseq_release_files:
      collection_subset: "vertebrate_mammalian"
      seqtype: "rna"
      filetype: "gbff"
      upload_list: []
      extension: ".gbk.db"

CompGenAnalysis_config:
  taxon_file: null
  go_list: null
  post_blast: true
  template: null
  save_data: true
  copy_from_package: true
  MAF: 'MAFV3.2.csv'

GenBank_config:
  solo: false
  multi: true
  min_fasta: true

Alignment_config:
  aln_program: 'GUIDANCE2'
  Guidance_config:
    seqFile: "C:\\Users\\rgilmore\\PycharmProjects\\OrthoEvolution\\OrthoEvol\\Manager\\config\\test.faa"
    msaProgram: "CLUSTALW"
    seqType: "nuc"
