Management_config:
  database: 'Test-Database'
  repo: 'Test-Repository'
  user: 'Test-User'
  project: 'Test-Project'
  research: 'Test-Research'
  research_type: 'Test-Research-Type'
  app: 'Test-App'
  website: 'Test-Website'
  host: '0.0.0.0'
  port: '5252'

CompGenAnalysis_config:
  taxon_file: null
  go_list: null
  post_blast: true
  template: null
  save_data: true
  copy_from_package: true
  MAF: 'MAFV3.2.csv'

GenBank_config:
  solo: false
  multi: true
  min_fasta: true

Alignment_config:
  aln_program: 'GUIDANCE2'
  project_path: null
