Full: "!!python/object/apply:pathlib.Path ['']"
NCBI: "!!python/object/apply:pathlib.Path ['NCBI']"
ITIS: "!!python/object/apply:pathlib.Path ['ITIS']"
NCBI_blast: "!!python/object/apply:pathlib.Path ['NCBI/blast']"
NCBI_blast_db: "!!python/object/apply:pathlib.Path ['NCBI/blast/db']"
NCBI_blast_windowmasker_files: "!!python/object/apply:pathlib.Path ['NCBI/blast/windowmasker_files']"
NCBI_pub_taxonomy: "!!python/object/apply:pathlib.Path ['NCBI/pub/taxonomy']"
NCBI_refseq_release: "!!python/object/apply:pathlib.Path ['NCBI/refseq/release']"
ITIS_taxonomy: "!!python/object/apply:pathlib.Path ['ITIS/taxonomy']"

